name: GovernanceOfColony
main: dev.ameruzily.campsystem.CampSystem
version: 1.0.7
api-version: '1.20'
authors: [ Ameruzily ]
description: State-based camp & war system (State refactor)
softdepend: [GraveX, PlaceholderAPI, RealisticSeasons, ItemsAdder]

commands:
  goc:
    description: Governance Of Colony main command
    usage: /goc
    aliases: []
    permission: camprpg.use

permissions:
  camprpg.use:
    default: true
  camprpg.admin:
    default: op
  camprpg.protection.bypass:
    default: op
